import type { Metadata } from "next";
import { Geist, Geist_Mono, Roboto } from "next/font/google";
import "./globals.css";

import Navigation from "@/components/Navigation";
import SidebarDesktop from "@/components/Sidebar/SidebarDesktop";
import BtnAdd from "@/components/BtnAdd";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const roboto = Roboto({
  variable: "--font-roboto",
  subsets: ["latin"],
  weight: ["400", "500", "700"]
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} ${roboto.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">
        <header>
          <Navigation />
        </header>

        <div className="flex">
          <aside className="hidden md:block border min-w-32 max-w-56 flex-1">
            <div>
              <SidebarDesktop />
            </div>
          </aside>

          <main className="border flex-1 relative p-4 md:p-5 lg:p-9">
            <div className="flex justify-between w-full">
              <div>
                <h1 className="text-3xl md:text-4xl">Welcome back, John!</h1>
              </div>
              <div className="hidden md:block">
                <BtnAdd />
              </div>
            </div>
            {children}
          </main>
        </div>
      </body>
    </html>
  );
}
